### PR TITLE
Updated Minecraft dependency to 1.19.2

### PR DESCRIPTION
**Pull request by apfohl**

### CODE REVIEW

**Comment by henkelmax** [comment]
I will update the mod, once I need it in the new version.

**Comment by apfohl** [comment]
I would really like to use it in the new version tho...

Would be nice to have it as I was looking for something simple like that for a long time. :pray: 

I appreciate the work.

**Comment by henkelmax** [comment]
You can just build your updated version. But this mod was made for the Hermitcraft server. They are still on 1.19. I don't want to maintain 2 different versions.

**Comment by apfohl** [comment]
Sure, I've done that already. And it works nicely. Would be nice to have it available in general. I can imagine more people will ask sooner or later, as Xisuma mentioned the mod in his last video. But all good for me now. ;)

**Comment by FixingGlobe** [comment]
Ah yes, thanks for all the vanilla enhancing mods.
Xisuma recently made publicity for your mods so probably lots of people will ask for 1.19.2 and I definitely understand not wanting to maintain 2 versions.
I've just copied over "depends" and "breaks" in fabric.mods.json from the 1.19.2 version of simple voice chat and no issues there on quilt 0.17.3 and 0.17.4

**Comment by henkelmax** [comment]
If you really want to use this mod on 1.19.2, just create a dependency override:
https://fabricmc.net/wiki/tutorial:dependency_overrides

**Pull request closed without merging**
